sudo: required
services:
  - docker

before_install:
  - docker build -t vnguyen0804/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vnguyen0804/react-test npm test -- --coverage

after_success:
  - docker build -t vnguyen0804/multi-client ./client
  - docker build -t vnguyen0804/multi-nginx ./nginx
  - docker build -t vnguyen0804/multi-server ./server
  - docker build -t vnguyen0804/multi-worker ./worker
  # Log in to the docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Taking those images and push to docker hub.
  - docker push vnguyen0804/multi-client
  - docker push vnguyen0804/multi-nginx
  - docker push vnguyen0804/multi-server
  - docker push vnguyen0804/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-complex
  env: DockerComplex-env
  bucket_name: elasticbeanstalk-us-east-1-487764425842
  bucket_path: docker-complex
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY