sudo: required
services:
  - docker

before_install:
  - docker-build -t vannguyen48/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run vannguyen48/react-test npm test -- --coverage

after_success:
  - docker build -t vannguyen48/multi-client ./client
  - docker build -t vannguyen48/multi-nginx ./nginx
  - docker build -t vannguyen48/multi-server ./server
  - docker build -t vannguyen48/multi-worker ./worker
  # Log in to the docker CLI.
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Taking those images and push to docker hub.
  - docker push vannguyen48/multi-client
  - docker push vannguyen48/multi-nginx
  - docker push vannguyen48/multi-server
  - docker push vannguyen48/multi-worker